### ISSUE TITLE
Module not working (does not launch): shapepcalib.py requires sklearn

### ISSUE THREAD

**Issue by bianchijonas1** [DCBIA-OrthoLab/ShapeVariationAnalyzer#49]
Hello. 
The module ShapeVariationAnalyzer is not working/being launched in the Slicer 4.11.0-2020-07-18! (Windows 10)
Maybe the figure bellow can help to solve this.
*Ps: I remember that I could use this module for the last time before the slicer change from python 2 to python3.

![image](https://user-images.githubusercontent.com/47431886/87989757-9ae56080-cab0-11ea-8f6a-1a701c0c02b4.png)

@jcfr @bpaniagua @luciacev

**Comment by jcfr** [comment]
The dependency on `sklearn` was introduced between June and September 2018 in b7705dc73a8ac523d6a553f6f522448426bb7fc1 and 14fb751a4338d0748e70aaba4671a32e6acfeeab to support PCA exploration:

https://github.com/DCBIA-OrthoLab/ShapeVariationAnalyzer/blob/b0dd7301f6be91975892031d6a02573c5e58f811/ShapeVariationAnalyzer/shapepcalib.py#L3

To address this, we will ensure `sklearn` is available by updating the extension build-system to install sklearn. Since the relevant build-system changes have already been done in SlicerSALT (see https://github.com/Kitware/SlicerSALT/commit/a42de30fb8a5b91de8b03886d4b7fe27cad6a8d6 ), we will migrate them to the extension
